version: '3.8'

services:
  frontend:
    build: ./frontend
    ports: 
      - "80:80"
    environment: 
      - REACT_APP_API_URL=http://localhost:3001
    depends_on: 
    - backend

  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      
      DATABASE_URL: '${DATABASE_URL}'
      COUNTRIES_API_BASE_URL: '${COUNTRIES_API_BASE_URL}'
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
      
      